"""Markdown export for Tour Guide journey reports."""

from pathlib import Path
from typing import List
from tour_guide.routing.models import Route
from tour_guide.models.poi import POI
from tour_guide.models.judgment import JudgmentResult


class MarkdownExporter:
    """
    Export journey data to Markdown format.

    Creates beautiful, readable Markdown reports with route overview,
    journey details for each POI, and summary statistics.
    """

    # Emoji mapping for content types
    EMOJI_MAP = {
        "youtube": "🎬",
        "spotify": "🎵",
        "history": "📖",
    }

    def __init__(self, version: str = "0.1.0"):
        """
        Initialize Markdown exporter.

        Args:
            version: Version number for the output
        """
        self.version = version

    def to_markdown(
        self,
        route: Route,
        pois: List[POI],
        judgments: List[JudgmentResult],
    ) -> str:
        """
        Convert journey data to Markdown string.

        Args:
            route: Route object with journey information
            pois: List of POI objects
            judgments: List of JudgmentResult objects

        Returns:
            Markdown formatted string
        """
        lines = []

        # Format origin and destination coordinates
        origin_coords = f"({route.origin[0]:.4f}, {route.origin[1]:.4f})"
        dest_coords = f"({route.destination[0]:.4f}, {route.destination[1]:.4f})"

        # Title
        lines.append(f"# 🗺️ Tour Guide: {origin_coords} → {dest_coords}\n")

        # Route Overview section
        lines.append("## Route Overview\n")
        lines.append(f"- **Distance**: {route.total_distance_km:.1f} km")

        duration_min = int(route.total_duration_min)
        hours = duration_min // 60
        mins = duration_min % 60
        duration_str = f"{hours}h {mins}m" if hours > 0 else f"{mins}m"
        lines.append(f"- **Duration**: ~{duration_str}")
        lines.append(f"- **Points of Interest**: {len(pois)}\n")

        # Journey section
        lines.append("## Journey\n")

        for i, (poi, judgment) in enumerate(zip(pois, judgments), 1):
            # POI header
            lines.append(f"### 📍 {i}. {poi.name}\n")
            lines.append(
                f"**Category**: {poi.category.value.title()} | "
                f"**Distance from start**: {poi.distance_from_start_km:.1f} km\n"
            )

            # Selected content
            selected_emoji = self.EMOJI_MAP.get(judgment.selected_type, "📄")
            lines.append(f"#### ⭐ Selected: {selected_emoji} {judgment.selected_type.title()}\n")
            lines.append(f"**{judgment.selected_content.title}**\n")
            lines.append(f"{judgment.selected_content.description}\n")
            lines.append(f"**Why selected**: {judgment.reasoning}\n")

            # All options
            lines.append("#### All Content Options\n")
            for content in judgment.all_content:
                emoji = self.EMOJI_MAP.get(content.content_type, "📄")
                lines.append(
                    f"- {emoji} **{content.content_type.title()}**: "
                    f"{content.title} (Score: {content.relevance_score})"
                )

            lines.append("\n---\n")

        # Summary section
        lines.append("## Summary\n")

        # Create content distribution table
        content_dist = {}
        for judgment in judgments:
            content_type = judgment.selected_type
            content_dist[content_type] = content_dist.get(content_type, 0) + 1

        lines.append("| Content Type | Count |")
        lines.append("|--------------|-------|")
        for content_type, count in sorted(content_dist.items()):
            emoji = self.EMOJI_MAP.get(content_type, "📄")
            lines.append(f"| {emoji} {content_type.title()} | {count} |")

        lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by Tour Guide v{self.version}*\n")

        return "\n".join(lines)

    def export(
        self,
        journey_data: str,
        output_path: Path,
    ) -> None:
        """
        Export Markdown string to file.

        Args:
            journey_data: Markdown formatted string (from to_markdown)
            output_path: Path where Markdown file will be written
        """
        # Ensure parent directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write Markdown file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(journey_data)

    def export_journey(
        self,
        route: Route,
        pois: List[POI],
        judgments: List[JudgmentResult],
        output_path: Path,
    ) -> None:
        """
        Convenience method to convert and export journey data in one step.

        Args:
            route: Route object
            pois: List of POI objects
            judgments: List of JudgmentResult objects
            output_path: Path where Markdown file will be written
        """
        markdown = self.to_markdown(route, pois, judgments)
        self.export(markdown, output_path)
